---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cat-gift
  labels:
    app: cat-gift
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cat-gift
  template:
    metadata:
      labels:
        app: cat-gift
    spec:
      containers:
      - name: cat-gift
        image: rostik5530/catnip
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: cat-gift
spec:
  selector:
    app: cat-gift
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cat-gift
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx-example
  rules:
  - host: "cat-gift.ru"
    http:
      paths:
      - path: /*
        pathType: Prefix
        backend:
          service:
            name: cat-gift
            port:
              number: 80


